---
- name: Update, install packages, and create a user
  hosts: vps_root
  remote_user: root

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade packages (dist-upgrade)
      apt:
        upgrade: dist

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Install Docker, Docker Compose, and UFW
      apt:
        name:
          - docker.io
          - docker-compose
          - build-essential
          - make
          - ufw
        state: present
        update_cache: yes

    - name: Create a new sudo user
      user:
        name: "{{ deploy_user }}"
        shell: /bin/bash
        groups: sudo,docker
        append: yes
        create_home: yes
        password: "{{ deploy_passwd }}"

    - name: Disable swap
      command: swapoff -a
      ignore_errors: yes

    - name: Remove existing swapfile
      file:
        path: /swapfile
        state: absent

    - name: Create 5GB swap file
      command: fallocate -l 5G /swapfile

    - name: Set correct permissions on swap file
      file:
        path: /swapfile
        owner: root
        group: root
        mode: "0600"

    - name: Make swap file
      command: mkswap /swapfile

    - name: Enable swap file
      command: swapon /swapfile

    - name: Make swap permanent in /etc/fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        state: present
